### ISSUE TITLE
Allow Clifford input circuits in CDR

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#1061]
This issue emerged from some questions on Discord.

Issue Description
-----------------
When using `mitiq.cdr.execute_with_cdr()` with a Clifford circuit produces the errir:
`ValueError: Circuit is already Clifford.
`
on the other hand, it may be more useful to return the mitigated result
which, in this case, is the exact classical simulation.

Proposed Solution
-----------------
If the input circuit is Clifford we could return the exact classically simulated expectation value.

**Comment by Rahul-Mistri** [comment]
I can add this feature. Are there any recommended papers/sources I ought to consult before giving this a go?

**Comment by nathanshammah** [comment]
Standard references on CDR are [Refs. [3,11] ](https://mitiq.readthedocs.io/en/latest/zz_bibliography.html) (together with the [Mitiq](https://arxiv.org/abs/2009.04417) white paper) and references therein.

**Comment by Rahul-Mistri** [comment]
I have two possible solutions but I could use some feedback:
1. Replace `raise ValueError(...)` with `return [circuit]*num_training_circuits` [here](https://github.com/unitaryfund/mitiq/blob/master/mitiq/cdr/clifford_training_data.py#L90). Returning the list of `num_training_circuits` copies of the Clifford circuit causes SciPy to raise a warning (that the covariance of parameters cannot be estimated) for specific circuits such as 
``` 
a, b = cirq.LineQubit.range(2)
circuit = cirq.Circuit(
    cirq.H.on(a),
    cirq.rx(np.pi / 2).on(b)
) 
```
and
``` 
a, b = cirq.LineQubit.range(2)
circuit = cirq.Circuit(
    cirq.H.on(a),
    cirq.H.on(b),
    cirq.CNOT.on(a,b)
) 
```
and I'm not sure why the warning is being raised. The correct answer (the classical simulation expectation value) is still calculated. A hacky fix is to suppress the specific warning.

2. The option I'm more keen on is to refactor [`generate_training_circuits(...)`](https://github.com/unitaryfund/mitiq/blob/master/mitiq/cdr/clifford_training_data.py#L35) by introducing a new function that determines if the circuit is a Clifford circuit. Then in [`execute_with_cdr`](https://github.com/unitaryfund/mitiq/blob/master/mitiq/cdr/cdr.py#L32), we check if the input circuit is Clifford using the new function, if it is, we immediately return the expectation value of the classical simulation. We can then remove this [check](https://github.com/unitaryfund/mitiq/blob/master/mitiq/cdr/clifford_training_data.py#L89-L90) since `generate_training_circuits(...)` is only called if the circuit isn't Clifford.

**Comment by andreamari** [comment]
+1 for the second option.
If the circuit is Clifford, CDR should not waste quantum and classical computation for training but directly return the exact result.
