### ISSUE TITLE
Update version of Cirq in core requirements

### ISSUE THREAD

**Issue by quosta** [unitaryfund/mitiq#1102]
Hello, I found that the lib with with numpy 1.22
Also other requirements like cirq are not up to the latest version. You might want to change the ~= to something like >=.

**Comment by andreamari** [comment]
Hi @quosta, I removed the bug label since this is the current expected behavior. 
We had several discussions on this in the past and we decided to pin the requirements. This reduces flexibility but improves reproducibility.

We will hopefully upgrade the requirements more recent versions in the next month. 

PS: This could be useful to force pip installing mitiq ignoring dependencies:  https://stackoverflow.com/questions/12759761/pip-force-install-ignoring-dependencies

**Comment by quosta** [comment]
Thank you @andreamari for your reply. It is indeed a sensible strategy to have a reliable workinglib ecosystem ()


```
>>> import mitiq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/mitiq/__init__.py", line 32, in <module>
    from mitiq import cdr, pec, rem, zne
  File "/usr/lib/python3.10/site-packages/mitiq/pec/__init__.py", line 20, in <module>
    from mitiq.pec.representations import (
  File "/usr/lib/python3.10/site-packages/mitiq/pec/representations/__init__.py", line 17, in <module>
    from mitiq.pec.representations.depolarizing import (
  File "/usr/lib/python3.10/site-packages/mitiq/pec/representations/depolarizing.py", line 22, in <module>
    from cirq import (
ImportError: cannot import name 'channel' from 'cirq' (unknown location)
```

**Comment by andreamari** [comment]
In #988 we are fixing this problem, including replacing `cirq.channel` with `cirq.kraus`.
Meanwhile, if this is urgent for you, you can try to install mitiq from source using the fork branch https://github.com/vtomole/mitiq/tree/patch-1 associated to #988.
