### ISSUE TITLE
Fix idle qubit register indexing

### ISSUE THREAD

**Issue by Aaron-Robertson** [unitaryfund/mitiq#1255]
Pre-Report Checklist
--------------------

- [x] I am running the latest version of mitiq
- [x] I checked to make sure that this bug has not already been reported

Issue Description
-----------------

Qiskit circuits built on registers like `qiskit.QuantumRegister(1) for _ in range(4)` insert (and remove) idle identities poorly, in particular when combined with DDD. Qubit index returns `0` for registers of the given type (and so other qubits are altered).

How to Reproduce
----------------

### Code Snippet

```python
import qiskit
from mitiq.ddd.insertion import insert_ddd_sequences
from mitiq.ddd.rules import xx, xyxy

qreg = [qiskit.QuantumRegister(1) for _ in range(4)]
circuit_qiskit_one = qiskit.QuantumCircuit(*qreg)
for q in qreg:
    circuit_qiskit_one.x(q)
    circuit_qiskit_one.x(3)

print(circuit_qiskit_one)
print(insert_ddd_sequences(circuit_qiskit_one, xyxy))
```
### Error Output
```
    ┌───┐                    
q0: ┤ X ├────────────────────
    ├───┤                    
q1: ┤ X ├────────────────────
    ├───┤                    
q2: ┤ X ├────────────────────
    ├───┤┌───┐┌───┐┌───┐┌───┐
q3: ┤ X ├┤ X ├┤ X ├┤ X ├┤ X ├
    └───┘└───┘└───┘└───┘└───┘
    ┌───┐┌───┐┌───┐┌───┐┌───┐┌───┐
q0: ┤ X ├┤ I ├┤ X ├┤ Y ├┤ X ├┤ Y ├
    ├───┤├───┤├───┤├───┤├───┤├───┤
q1: ┤ X ├┤ I ├┤ X ├┤ Y ├┤ X ├┤ Y ├
    ├───┤├───┤├───┤├───┤├───┤├───┤
q2: ┤ X ├┤ I ├┤ X ├┤ Y ├┤ X ├┤ Y ├
    ├───┤├───┤├───┤├───┤├───┤├───┤
q3: ┤ X ├┤ X ├┤ X ├┤ X ├┤ X ├┤ I ├
    └───┘└───┘└───┘└───┘└───┘└───┘

**Comment by andreamari** [comment]
Assigned to @Rahul-Mistri !

**Comment by natestemen** [comment]
Can someone who has a bit more context here please provide what the expected output is? @Aaron-Robertson @andreamari @Rahul-Mistri

**Comment by andreamari** [comment]
I think the expected result is the following:

```
     ┌───┐                    
q_0: ┤ X ├────────────────────
     ├───┤                    
q_1: ┤ X ├────────────────────
     ├───┤                    
q_2: ┤ X ├────────────────────
     ├───┤┌───┐┌───┐┌───┐┌───┐
q_3: ┤ X ├┤ X ├┤ X ├┤ X ├┤ X ├
     └───┘└───┘└───┘└───┘└───┘
     ┌───┐┌───┐┌───┐┌───┐┌───┐
q_0: ┤ X ├┤ X ├┤ Y ├┤ X ├┤ Y ├
     ├───┤├───┤├───┤├───┤├───┤
q_1: ┤ X ├┤ X ├┤ Y ├┤ X ├┤ Y ├
     ├───┤├───┤├───┤├───┤├───┤
q_2: ┤ X ├┤ X ├┤ Y ├┤ X ├┤ Y ├
     ├───┤├───┤├───┤├───┤├───┤
q_3: ┤ X ├┤ X ├┤ X ├┤ X ├┤ X ├
     └───┘└───┘└───┘└───┘└───┘
```

**Comment by Misty-W** [comment]
hi @Rahul-Mistri, wanted to check if you're planning to work on this issue in the current milestone (0.21, closes Nov 30). If not, no worries, someone on the Mitiq team can pick this up.

Happy to help clear any roadblocks!

**Comment by natestemen** [comment]
I took a look at this today and it seems to be a bit thorny. The problem goes away if one defines their circuit using a single register:
```
qreg = qiskit.QuantumRegister(4)
circuit_qiskit_one = qiskit.QuantumCircuit(qreg)
...
```
I'm not familiar enough with Qiskit to know if both are widely used, but it would be good to have these functions work regardless of how a user defined their circuit.

The problem arises because we use the `index` attribute of [`Qubit`](https://qiskit.org/documentation/stubs/qiskit.circuit.Qubit.html) objects, which is register dependent, and hence how one defines their circuit affects the results of both https://github.com/unitaryfund/mitiq/blob/6af27485859e1b284d2607d5ef901078a303931b/mitiq/interface/mitiq_qiskit/conversions.py#L121-L123 and https://github.com/unitaryfund/mitiq/blob/6af27485859e1b284d2607d5ef901078a303931b/mitiq/interface/mitiq_qiskit/conversions.py#L150-L153

This issue, should probably be address in tandem with https://github.com/unitaryfund/mitiq/issues/1422. In fact they may be the same issue, really.

@Rahul-Mistri do you have any notes on this that differ/agree with my understanding?
