### ISSUE TITLE
benchmarks.mitiq.dev is down

### ISSUE THREAD

**Issue by 1ucian0** [unitaryfund/mitiq#1410]
The README file refers to https://benchmarks.mitiq.dev/ which is 404ing.
<img width="618" alt="Screenshot 2022-07-26 at 15 47 09" src="https://user-images.githubusercontent.com/766693/181021701-fa3fa5cd-3b8f-414b-9c15-4296c166e81a.png">

**Comment by 1ucian0** [comment]
Maybe it should point to https://metriq.info/Submission/18 ?

**Comment by natestemen** [comment]
Thanks Luciano. The site is live at https://unitaryfund.github.io/mitiq-bench/, and refers to a different type of benchmark than what metriq does. We do have https://github.com/unitaryfund/mitiq-bench/issues/1 open to fix this issue because it should be live at `benchmarks.mitiq.dev`, but I just haven't gotten around to it yet. Since we have the other issue, I'll close this for now.
