### ISSUE TITLE
Unable to batch with multiple circuits with Qiskit. 

### ISSUE THREAD

**Issue by Amai-RusseMitsu** [unitaryfund/mitiq#1460]
Dear Mitiq team, 

I was wondering if anyone has successfully used Mitiq and batched execute using the Execute function on the qiskit backend. I have a IBMQ account and whenever I use batched Execute according to the following guide https://mitiq.readthedocs.io/en/stable/guide/executors.html. Qiskit interprets this not as a batched job but as multiple single jobs that are being sent, with the next job only being sent when the previous one is done. Given I have 900+ circuits in one job, the bottleneck becomes the queue not so much the computation.  This also makes retrieval of the jobs from the IBMQ backend difficult since I have many separate job IDs that I need to call and this quickly becomes unfeasible. 

In this regard, I would like to ask if anyone has successfully managed to batch execute on the qiskit backend with all specified circuits in a qc_list being sent at one go rather than one by one with Mitiq; and if there is a workaround for this. If the answer is yes, I was wondering if there is any documentation available because I can't seem to find any.

As a minimal example, just to illustrate the problem, suppose we have the following sets of executors)
```
def executor(circuit: QuantumCircuit,backend_name: str = user_backend, shots: int = shot_num) -> float:
        qobj = execute(circuit, backend, shots = shot_num).result()
        return expectation_value() #This is a function I defined on my own

def batch_run_zne(circuits: List[QuantumCircuit]) -> List[float]:
    return [zne.execute_with_zne(circuits[j],executor) for j in tqdm(range(len(circuits)))]

def run_zne(qc_list):
    return Executor(batch_run_zne, max_batch_size=100000).evaluate(qc_list,force_run_all = True)

expectation_zne = run_zne(qc_list) #Step to batch run executor. 
```
It is difficult to provide a working example since that requires an api key for the backend

Thanks in advance!!! 👍 
https://www.loom.com/share/09bd99dc7e1c4453a15a0379945f6314

**Comment by andreamari** [comment]
Thanks @Amai-RusseMitsu  for reporting this issue in a very detailed way. The loom link is cool! 

I think what is going on here is that the Executor object is indeed calling `batch_run_zne` a single time as expected but, since in the code of `batch_run_zne` all the circuits are executed one-by-one, batching is lost from a practical point of view.

This is a sketch of a valid unmitigated batched executor that should work:

```
def batch_run(circuits: List[QuantumCircuit]) -> List[float]:
        # Send all circuits to the backend as single batch
        qobj = execute(circuits, backend, shots = shot_num).result()
        return expectation_values_for_all_circuits(qobj)    # To be defined

#Step to batch run executor. 
expectation_values =Executor(batch_run, max_batch_size=100000).evaluate(qc_list,force_run_all = True) 
```

However, as you can see, I had to remove the ZNE layer. 
The reason is that `zne.execute_with_zne()` can take as input just a single circuit. I.e. `zne.execute_with_zne()` doesn't  currently support the application of ZNE to a batch of circuits, it just mitigates a **single circuit** by running a batch of auxiliary circuits under the hood. 

If you want to apply ZNE to a batch of circuits, you probably need to generalize to many circuits the low-level workflow discussed [here](https://mitiq.readthedocs.io/en/stable/guide/zne-4-low-level.html), in which circuits are first folded, then executed (possibly with batching) and finally the noise scaled expectation values are extrapolated.
