### ISSUE TITLE
Mitiq FAQ's in the discussion forum

### ISSUE THREAD

**Issue by purva-thakre** [unitaryfund/mitiq#1936]
These FAQ's will have a section directing a person to the FAQs first. If their question is not in the list of FAQs then a section to think about & describe their problem in detail (https://blog.codinghorror.com/rubber-duck-problem-solving/). 

**What are some of the most common mitiq related questions asked by users?** These could go into the FAQ's of the discussion forum. Format: `Common problem - solution to the common problem`

Feel free to add these questions as comments below which will be used to create a pinned post in the discussion forum.

**Comment by jordandsullivan** [comment]
Starting to draft FAQs:

**1. What is quantum error mitigation?**
Quantum error mitigation (QEM) refers to a series of techniques aimed at reducing (mitigating) the errors that occur in quantum computing algorithms. Unlike software bugs affecting code in usual computers, the errors which we attempt to reduce with mitigation are due to imperfections in the hardware. Quantum error mitigation techniques try to reduce the impact of noise in quantum computations. They generally do not completely remove it. For more info on QEM, check out this [docs article](https://mitiq.readthedocs.io/en/stable/guide/error-mitigation.html#what-is-quantum-error-mitigation). 

**2. What do ZNE/PEC/DDD/etc. mean?**
[Zero Noise Extrapolation](https://mitiq.readthedocs.io/en/stable/guide/error-mitigation.html#zero-noise-extrapolation), [Probabilistic Error Cancellation](https://mitiq.readthedocs.io/en/stable/guide/pec.html), and [Digital Dynamical Decoupling](https://mitiq.readthedocs.io/en/stable/guide/ddd.html). These are acronyms for quantum error mitigation techniques, which you can find along with other frequently used acronyms in our [wiki](https://github.com/unitaryfund/mitiq/wiki/Common-Acronyms).

**3. What QEM techniques are available in mitiq?**
_This is where it would be useful to have method to get a list of all available qem methods, e.g. https://github.com/unitaryfund/mitiq/issues/2244 . We could then query this method using jupytext as usual when inserting code with outputs into our docs. Otherwise, we can manually list them out. Alternatively, we could rearrange the user guide to have a directory structure similar to the proposal in https://github.com/unitaryfund/mitiq/issues/2245, with a parent directory  called something like QEM Methods (on the same level as https://mitiq.readthedocs.io/en/stable/guide/core-concepts.html), containing a list of all the available QEM methods whose articles are currently on the top-level._

**4. How should I choose a QEM technique for my use case?**
We recommend trying out our [calibration module](https://mitiq.readthedocs.io/en/stable/guide/calibrators.html), which can help you choose between different QEM methods and spend less time optimizing parameters.

**5. Are you planning to add support for [feature/toolkit/library]?**
You can check out our [roadmap](https://github.com/unitaryfund/mitiq/wiki#mitiq-2024-roadmap) to see what we currently have planned. If you don't see your specific request there, have a look through our [open issues](https://github.com/unitaryfund/mitiq/issues?q=is%3Aissue+is%3Aopen) and see if you find one that matches what you're looking for; you can then add a comment sharing your interest or get started working on it yourself (hint: be sure to take a look at our [Contribution Guide](https://mitiq.readthedocs.io/en/stable/toc_contributing.html) to get started).

**Comment by jordandsullivan** [comment]
@natestemen do you want to have a look at the above FAQs and see if you would add any other ones to start with?

**Comment by purva-thakre** [comment]
Not Nate but I think there could be a FAQ pointing to the core concepts page in the docs. https://mitiq.readthedocs.io/en/stable/guide/core-concepts.html

**Comment by jordandsullivan** [comment]
All good! Added, and let me also extend the invitation to anyone else who would like to append or edit FAQ suggestions :)

**Comment by purva-thakre** [comment]
@natestemen Since we are planning to restrict all Mitiq-related technical questions to `Discussions`,  re-directing the user to the documentation won't work that well if they have to toggle back and forth from `Discussion` to the docs. 

We can [create](https://docs.github.com/en/discussions/managing-discussions-for-your-community/managing-categories-for-discussions) a new `FAQs` category in `Discussions`. This is better than a pinned post. 

Also, in addition to the nice list by @jordandsullivan, should we add a section on how to ask a technical question properly? I don't have any additional ideas beyond linking the `Rubber duck problem solving` page. My personal opinion is that a user asking us for help by dumping a bunch of code in their post without providing additional details doesn't work that well.

**Comment by jordandsullivan** [comment]
One idea on that would be to create templates for our existing discussion
categories:
https://github.blog/2023-01-09-github-discussions-just-got-better-with-category-forms/
.

I do think a short primer on rubber duck decoding would also be good,
though I'm not sure an FAQ would be the best place for it, since "how
should I ask a technical question?" doesn't necessarily seem something like
most people would have the self-awareness to ask.

Best,
Jordan Sullivan

**Comment by natestemen** [comment]
I do feel like this is a bit of a premature optimization. We have a total of 22 total discussion posts since we started using Discussions in July of 2023. Only 8 of these posts were opened by external folks, of which I'd say 3-4 of could have used some extra guidance when crafting their question. Sure, it takes some more time to get to the bottom of what the issue is when people post tons of code without hints as to where the problem actually is, but we need to meet people where they are.

Purva originally suggested a format of `Common problem - solution to the common problem`, and as much as I love that, we don't really have enough feedback to know what the common problems are. Further, I don't want to inhibit anyone from getting in touch with us because we have some hoops to jump through to ask questions. If we do want to remind people to ask thoughtful questions, what if we make a discussion post about asking questions (meta), and link to a resource like https://stackoverflow.com/help/how-to-ask? WDYT?

FWIW I still think an FAQ is still a helpful resource, but we want to make sure not to duplicate info across it, the [glossary](https://mitiq.readthedocs.io/en/stable/guide/glossary.html), and the [about QEM](https://mitiq.readthedocs.io/en/stable/guide/error-mitigation.html) pages.

**Comment by purva-thakre** [comment]
> Further, I don't want to inhibit anyone from getting in touch with us because we have some hoops to jump through to ask questions.

@natestemen Yes, I agree with you on this. 

Fine by me if we skip the suggested format.

I still think there should at least be a guide on how to ask a question (meta post with SO links should work) and a way to verify if they have read the documentation before asking the question. This does get to your comment about 'meeting people where they are'. Getting through to someone over multiple back-and-forth comments can also take some effort in cases when the only response is to reword the statement 'go over the examples in the documentation' in different ways. 

Also, in the meta post, can we provide an estimated timeline for when we can respond to their discussions and comments? Lets us off the hook if they are working on an immediate deadline and we can't respond ASAP.

**Comment by jordandsullivan** [comment]
I like the general direction @purva-thakre, though I do worry that the list you suggested is a bit of a heavy lift and may discourage some newcomers. Also, not all mitiq questions will necessarily involve an executor. I also think there's overlap between Problem Setup and Context

**Comment by purva-thakre** [comment]
@jordandsullivan Sure! I'll leave it up to you and stop with the suggestions. :)

As long as we have a process where we make the user think before [asking a question](https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/), things should work out in the end. From personal experience, whenever I needed to ask a technical question on some forum, the process of thinking to communicate ended up helping me find a solution to my question. 

http://catb.org/esr/faqs/smart-questions.html

**Comment by jordandsullivan** [comment]
Please feel free to keep the suggestions flowing @purva-thakre ! I'm also happy to drive this if you like :)
I definitely agree the process of crafting an effective question can help in someone's understanding.

> http://catb.org/esr/faqs/smart-questions.html

This is an interesting guide. I agree with some of their best practices there, but ngl it also feels almost intentionally exclusionary, requiring a relatively high barrier to entry that not everyone has the background, experience, or importantly _time_, to build up. 
I think to be more inclusive, maybe we can come up with a slightly friendlier guide to asking a good question, compiled from several of the resources already shared above. 

I think we can have one post with FAQs (like the ones above) and another pinned post on how to ask a good question.  
My draft is below. One thing I still have a question on is how we want people to use our Discord server. I know I often use Discord as a shortcut to get questions answered more quickly, but I know what I've listed below are really best practices.

**Comment by jordandsullivan** [comment]
### How to ask a good question 
The world of quantum computing moves at a fast pace, and we all have questions! We've found that the process of _thinking through how to communicate your problem_ to another person  -- including [writing as a form of thinking](https://www.insidehighered.com/blogs/higher-ed-gamma/writing-thinking) -- often ends up helping you find a solution to your problem.

So, before posting your question here on the Discussions page, we suggest going through the steps below:

**1. Try to find an answer by reading our FAQs [link].** You can also check out any discussions currently open [link]. 

**2. Try to find an answer by checking out our [Mitiq Documentation](https://mitiq.readthedocs.io/en/stable/)**. We try to make these really clear, and reading through them should give you a good sense of Mitiq's fundamental components.

**3. Try to find an answer by checking out our [Mitiq Examples](https://mitiq.readthedocs.io/en/stable/examples/examples.html)**.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; a. Look for one that includes the problem you're trying to solve, and try to match your code with a similar example. 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; b. Is there anything present in the example code that you're missing? Experiment with small changes and try to isolate &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;where the problem is coming from.

**4. Try to find an answer by searching the Web.** Search for any error messages + the relevant packages you're working with. [StackExchange](https://stackexchange.com/), [StackOverflow](https://stackoverflow.com/), and [Quantum Computing Stack Exchange](https://quantumcomputing.stackexchange.com/) are your friends here.

**5. Try to find an answer by reading the Mitiq source code.** Check out the code that defines the function you're calling or the module you're working with. If you get an error that references a line in a specific file, go ahead and try find it.

_If you still haven't found the answer to your question, you can use what you've learned so far to..._

**6.  Write out your question like you were trying to explain it to a busy colleague** and have to sum up your entire question in one sentence: what details can you include that will help someone identify and solve your problem? Include any error messages, key APIs, or unusual circumstances that make your question different from similar questions in the Mitiq FAQs[link] or [examples](https://mitiq.readthedocs.io/en/stable/examples/examples.html) as well as any forums you tried. 
Hint: it might help to try imagining you're [explaining your problem to a rubber duck](https://blog.codinghorror.com/rubber-duck-problem-solving/)!

**7. Create a Discussion post of the relevant type and paste your question from step 6. into the description. Be sure to include a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).**

If you're followed all these steps, you 

Adapted from these resources:
http://catb.org/esr/faqs/smart-questions.html, 
https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/,  
https://stackoverflow.com/help/how-to-ask,
https://blog.codinghorror.com/rubber-duck-problem-solving/

**Comment by purva-thakre** [comment]
> but ngl it also feels almost intentionally exclusionary, requiring a relatively high barrier to entry that not everyone has the background, experience, or importantly time, to build up

Yep, I agree. I linked it so that we could pick and choose the better parts and discard the rest. Last night, I went down the rabbit hole of what drives the SO culture and how they tried to improve it, came across the two links in my previous comment.

**Comment by jordandsullivan** [comment]
Totally makes sense. 

So I think the action items here are

- [ ] Create an FAQ (let's start with the draft above and we can iterate) in Discussions
- [ ] Pin the FAQ (see screenshot below) 
<img width="318" alt="Screen Shot 2024-04-12 at 1 42 13 PM" src="https://github.com/unitaryfund/mitiq/assets/15827191/701fa44e-0004-4c4d-b83b-ed34772a8b05">
- [ ] Create the How to ask a good question guide as a post in Discussions
- [ ] Pin How to ask a good question guide at the very top

Any objections?

**Comment by purva-thakre** [comment]
> Any objections?

@jordandsullivan None from me about the two pinned posts. Looks great!

At Step 7 of `How to ask a good question`, a statement about their discussion/comments will get a response from us within 24 hours of a weekday could be added. There have been instances of someone pinging people in the Discord channel on a weekend when they were working on an urgent deadline.  

You did bring up a good question of how we want to use the Discord server. If all technical discussions are moved to Github, I am also drawing blank on what the Discord channel could be used for. We could discuss this later during a community call when we can get feedback from everyone.

**Comment by jordandsullivan** [comment]
As for category updates, I know we talked about adding a new FAQ category, which I could see as a way to get to a pinned post showing FAQs, but as for other questions, are we thinking we would move questions to this category after they were posted if they seemed to be coming up a lot in the Q&A?

<img width="329" alt="Screen Shot 2024-04-12 at 1 56 16 PM" src="https://github.com/unitaryfund/mitiq/assets/15827191/7a5a66a6-f739-4c29-8972-b08856379dd9">

**Comment by jordandsullivan** [comment]
Okay, @purva-thakre I added [FAQ](https://github.com/unitaryfund/mitiq/discussions/2358) and [How to ask a good question](https://github.com/unitaryfund/mitiq/discussions/2359) pages in our Discussions and pinned them in Q&A:

<img width="1379" alt="Screen Shot 2024-05-09 at 9 46 26 AM" src="https://github.com/unitaryfund/mitiq/assets/15827191/f9290026-054c-4391-9f31-1b0ac57f4eb1">

How do we feel about closing this issue?

**Comment by purva-thakre** [comment]
Thanks Jordan!

**Comment by purva-thakre** [comment]
@jordandsullivan Should we remove the `Q&A` category? 

Github discussions lets you pin something globally or in a category. I just tried to pin both and they ended up getting pinned in the `Q&A` category. 

https://docs.github.com/en/discussions/managing-discussions-for-your-community/managing-discussions#pinning-a-discussion-globally

**Comment by jordandsullivan** [comment]
It looks like they're both pinned globally now :) 
<img width="1414" alt="Screen Shot 2024-05-10 at 8 36 31 AM" src="https://github.com/unitaryfund/mitiq/assets/15827191/9860200b-df4e-4427-9ed4-b5a764b01220">

**Comment by jordandsullivan** [comment]
I think we should keep the Q&A category, it's useful :)
