### ISSUE TITLE
Reduce documentation build time

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#2024]
## Issue Description
The documentation build time has roughly doubled from 30 minutes to about 60 minutes after adding the classical shadows documentation. 

## Proposed Solution
Some data could be copied in a file and not really generated at documentation build, especially for the section "1. How do I use classical shadows estimation?", which takes a long time to build.

**Comment by bdg221** [comment]
@Misty-W  please assign this issue to me. 

I have done some research and found:
![image](https://github.com/unitaryfund/mitiq/assets/62308289/05301e7f-f1ec-48aa-b086-2f8b3cde9b85)

I am first looking at the examples/rshadows_tutorial.md. I have taken the files that are pulled from the github repository and put them into a docs/source/resources folder. I tested locally and did see some speed up, though I was not seeing the same delays that the build from a PR sees. I'll be submitting a PR for testing purposes. 

Also, I did leave a commented out version of the code using the repo.

**Comment by purva-thakre** [comment]
@bdg221 Some parts of `guide/shadows` and `rshadows_tutorial` rely on quantum processing of the circuits (number of snapshots) which takes a lot of time. 

If the output of these quantum processing steps is saved as a resource in the form of a text file, it could help shorten the time because RTD does not have to rerun those codeblocks for every commit.

Pinging @Misty-W @natestemen @andreamari just in case
