### ISSUE TITLE
DDD + ZNE tutorial.

### ISSUE THREAD

**Issue by cosenal** [unitaryfund/mitiq#2344]
I can plan to contribute on the examples section of this issue with a DDD + ZNE tutorial.

_Originally posted by @jordandsullivan in https://github.com/unitaryfund/mitiq/issues/2288#issuecomment-2067117771_

**Comment by jordandsullivan** [comment]
Warning: this comment may not read clearly to anyone but me. Trying to document errors that arise as I go. Will clean up and provide more context next week. 

If you try to pass a partial (the functools utility) executor function, something like `ideal_exec = partial(execute, rz_noise = 0.001, depolar_noise = 0.005)` in as your executor in `zne.mitigate_executor`, 
 the return type checks in mitiq.executor:
https://github.com/unitaryfund/mitiq/blob/b58f0294cdce9e1c38d17c1faa67348983065006/mitiq/executor/executor.py#L181-L207 
throw the following error:
```
File "/Users/jordansullivan/UnitaryFund/mitiq/mitiq/executor/executor.py", line 205, in evaluate
    raise ValueError(
  File "/Users/jordansullivan/UnitaryFund/mitiq/mitiq/zne/inference.py", line 568, in run
    res = executor.evaluate(
  File "/Users/jordansullivan/UnitaryFund/mitiq/mitiq/zne/zne.py", line 61, in execute_with_zne
    return factory.run(
  File "/Users/jordansullivan/UnitaryFund/mitiq/mitiq/zne/zne.py", line 98, in new_executor
    return execute_with_zne(
  File "/Users/jordansullivan/UnitaryFund/mitiq/docs/source/examples/combine_ddd_zne.py", line 145, in <module>
    combined_result = combined_executor(circuit)
ValueError: Could not parse executed results from executor with type typing.Union[float, typing.Tuple[float, typing.Dict[str, typing.Any]]].
```

**Comment by jordandsullivan** [comment]
Let's say we're working with the following executor:
```Python
def execute(
    circuit: cirq.Circuit, 
    rz_noise: float = 0.01,
    depolar_noise: float = 0.0005
    ) -> MeasurementResult:
    """
    Execute a circuit with R_z dephasing noise of strength ``rz_noise`` and 
    depolarizing noise ``depolar_noise``
    """
    # Simulate systematic dephasing (coherent RZ) on each qubit for each moment.
    circuit = circuit.with_noise(cirq.rz(rz_noise))

    # Simulate systematic depolarizing on each qubit for each moment.
    circuit = circuit.with_noise(cirq.bit_flip(depolar_noise))

    simulator = cirq.DensityMatrixSimulator()

    result = simulator.run(circuit, repetitions=1000)
    
    bitstrings = np.column_stack(list(result.measurements.values()))
    return MeasurementResult(bitstrings)
```
Which returns a list of measurement bitstrings  (i.e. it doesn't calculate an expectation value).
First off, I am confused that calling `execute(circuit)` for some valid `cirq.circuit` throws the following error:
`ValueError: Circuit has no measurements to sample.` (The full traceback is very long, not particularly instructive).

**Comment by jordandsullivan** [comment]
Yet another separate error comes up when I indeed combine the two executors which work individually

```Python
from mitiq import Observable, ddd

obs = Observable(PauliString("ZI"), PauliString("IZ"))

rule = ddd.rules.yy
ddd_executor = ddd.mitigate_executor(noisy_exec, observable=obs, rule=rule)
```
into zne.mitigate_executor:
```Python
combined_executor = zne.mitigate_executor(ddd_executor, scale_noise=zne.scaling.folding.fold_global)

combined_result = combined_executor(circuit)
```
I am not certain if I am meant to pass the observable in both the ddd_executor function and the mitigate_executor one, but if I do not pass it, as shown above, I find that the multiple runs of ddd do indeed complete; however, when it tries to combine all the results after the various circuits have run in ZNE, since on the top level of the call stack, `observable=None`, these lines fail:
https://github.com/unitaryfund/mitiq/blob/b58f0294cdce9e1c38d17c1faa67348983065006/mitiq/executor/executor.py#L197-L200 

I tried also passing the observable to both executors:
```Python
combined_executor = zne.mitigate_executor(ddd_executor, observable=obs, scale_noise=zne.scaling.folding.fold_global)
```
And in this case it throws an error from inside the execute function (defined in previous comment), because somehow the result variable
`result = simulator.run(circuit, repetitions=1000)` 
has no measurements.

**Comment by Misty-W** [comment]
> I am confused that calling `execute(circuit)` for some valid `cirq.circuit` throws the following error: `ValueError: Circuit has no measurements to sample.` Am I maybe using the wrong result type for this circuit?

I believe this error is occurring because `with_noise` is adding noise after the measurement. That's one reason we often add measurements in the executor instead of in the original circuit.

**Comment by Misty-W** [comment]
> Because the type of `self._executor_return_type` for `functools.partial` is is `None`. So do we advise people not to use partial functions? Or do we skip this check in the case of a partial executor?

This error is most likely coming from the ["not having terminal measurements" problem] (https://github.com/unitaryfund/mitiq/issues/2344#issuecomment-2096699957) and not the use of `partial`.

**Comment by Misty-W** [comment]
> I am not certain if I am meant to pass the observable in both the ddd_executor function and the mitigate_executor one, 

Yes, the observable should be passed in both. Hopefully moving the measurements to the executor solves the chain of errors and issues!

**Comment by Misty-W** [comment]
@jordandsullivan, I believe the root cause of the issues described here is the executor's insertion of noise ops after (what are intended to be) terminal measurements in the circuit. 

The easiest way to work around this is to create a circuit without measurements and pass it to the executor which adds measurements after adding noise.

**Comment by jordandsullivan** [comment]
The solution which seemed to solve this issue was
1. Adding in measurements after the calls to `circuit.with_noise` within the `execute` function as follows:
```Python
...
  # Measure out all qubits
  circuit += cirq.measure(*sorted(circuit.all_qubits()), key="m")
  # Use a noise simulator
  simulator = cirq.DensityMatrixSimulator()
  # Run the circuit 1000 times
  result = simulator.run(circuit, repetitions=1000)
  
  # Retrieve the measurement results in bitstring form
  bitstrings = result.measurements["m"]
  return MeasurementResult(bitstrings)
  ```
2. Switching from using `ddd.mitigate_executor()` as the execute function which I pass to the `zne.mitigate_executor()` function and instead modifying the _`circuit`_ itself by applying `ddd.insert_ddd_sequences()`, then passing this to the final `combined_executor`:
```Python
from mitiq.ddd import rules, insert_ddd_sequences

rule = rules.yy
ddd_circuit = insert_ddd_sequences(circuit, rule)

combined_executor = zne.mitigate_executor(execute, observable=obs)
combined_result = combined_executor(ddd_circuit)


```
