### ISSUE TITLE
Broken Qiskit logo in the readme

### ISSUE THREAD

**Issue by purva-thakre** [unitaryfund/mitiq#2417]
![image](https://github.com/unitaryfund/mitiq/assets/66048318/1bd9884a-f35f-49b4-81ca-b0c815c496df)

https://github.com/unitaryfund/mitiq?tab=readme-ov-file#supported-frontends

**Comment by natestemen** [comment]
I actually cannot find the Qiskit logo anywhere on the [IBM Quantum](https://www.ibm.com/quantum/) or [Qiskit documentation](https://docs.quantum.ibm.com/start/hello-world) websites...

Maybe this means they are either transitioning away from it. Either way, I guess a solution is to download an image online and store it in the repo instead of using a linked image.
