### ISSUE TITLE
Noise characterization tutorial: IC - ZNE

### ISSUE THREAD

**Issue by purva-thakre** [unitaryfund/mitiq#2564]
As we start to scope how noise characterization in Mitiq might look like, a tutorial demoing ZNE with noise characterization would be helpful. 

https://arxiv.org/abs/2403.01608v1

Nate's QW talk: https://drive.google.com/file/d/1vTkIBZGOR5sE6Id96e1F-jRX2xg6eH9B/edit

**Comment by Shivansh20128** [comment]
Hi @purva-thakre , the inverted circuit ZNE looks interesting to me. I have gone through the slides in Nate's QW talk, and am looking forward to learn more. Do you think I can help with this? I know the deadline is closing upon us, but still I would like to work on this if no one else is.
Since we need to make a "tutorial demoing ZNE with noise characterization", could you also give me an example of what a tutorial looks like.
Thank you

**Comment by purva-thakre** [comment]
> Do you think I can help with this?

No, sorry. I have a working version already. I just haven't pushed it yet because I need to clean it up first. Thanks!

**Comment by Shivansh20128** [comment]
Okay!

**Comment by purva-thakre** [comment]
Closing this as IC-ZNE implementation is better as an optional arg in `execute_with_zne` instead of a tutorial.

**Comment by natestemen** [comment]
@purva-thakre I believe you mentioned you had a tutorial in the works. Can you link a [gist](https://gist.github.com/) of what you had put together so far in terms of a tutorial? This can help inform future work.
