### ISSUE TITLE
Codecov failing on master

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#322]
https://github.com/unitaryfund/mitiq/runs/1004073495

Apparently due to a timeout error.

![image](https://user-images.githubusercontent.com/32416820/90678518-c7fe6d80-e22c-11ea-938f-c45a7953d07b.png)

Any ideas what's going on here? @nathanshammah @karalekas

**Comment by willzeng** [comment]
I re-ran the tests on master and they passed. It looks like this error also happened for #285

**Comment by nathanshammah** [comment]
No idea.

**Comment by nathanshammah** [comment]
https://github.com/codecov/codecov-action/issues/37

**Comment by karalekas** [comment]
afaik this happens when the codecov API times out. simply re-running the test should be sufficient. as you can see, I enabled `fail_ci_if_error: true` (which I think they added for exactly this reason). if this becomes a persistent issue, we could consider disabling the error flag, but that would somewhat defeat the purpose of having a code coverage tool

**Comment by willzeng** [comment]
Looks like this is not something to do with our own infrastructure. I'd propose we close this for now and if it becomes a big enough hassle then we can re-open and maybe switch coverage tooling.
