### ISSUE TITLE
Make RTD point to stable version. Update links from latest to stable.

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#353]
See #349 and comment by @andreamari for context: 
- If possible, build the docs on Read The Docs (RTD) also for mitiq v.0.1.0, so that we can point with persistent links there, where relevant, e.g., from the arXiv paper, which documents v.0.1.0. 
- Enable mitiq/stable as default version that one sees at https://mitiq.readthedocs.io/. 
- Update links in repo and documentation to point to stable versions.

**Comment by rmlarose** [comment]
Comment from #349:

**Comment by karalekas** [comment]
TODO: Add @crazy4pi314 as an owner on RTD project.

**Comment by crazy4pi314** [comment]
Making a todo list:
- [ ] If possible, build the docs on Read The Docs (RTD) also for mitiq v.0.1.0, so that we can point with persistent links there, where relevant, e.g., from the arXiv paper, which documents v.0.1.0.
- [ ] Enable mitiq/stable as default version that one sees at https://mitiq.readthedocs.io/.
- [x] Update links in repo and documentation to point to stable versions.

**Comment by crazy4pi314** [comment]
@karalekas is there a config login/panel for RTD outside of the repo?

**Comment by crazy4pi314** [comment]
- [ ] Investigate what is going on with the automated API docs generation for this section

> Comment from #349:
> 
> https://mitiq.readthedocs.io/en/latest/apidoc.html#module-mitiq.zne.scaling is just a blank section?
> 
> ![image](https://user-images.githubusercontent.com/32416820/92656750-958ee000-f2c1-11ea-846d-82e7cff16378.png)
> 
> > See #349 and comment by @andreamari for context:

**Comment by karalekas** [comment]
@crazy4pi314 I've opened a new issue #407 to track your last comment, and thus closing this issue
