### ISSUE TITLE
Bayesian ZNE estimation

### ISSUE THREAD

**Issue by crazy4pi314** [unitaryfund/mitiq#418]
Pre-Request Checklist
---------------------

- [x] I am running the latest version of mitiq
- [x] I checked to make sure that this feature has not already been requested

Issue Description
-----------------

I think our current approach of using MLE in factories to estimate fit parameters is not the best approach to estimating what we want to learn which is the ZN limit. 
I am not sure we are currently meeting the assumptions needed to use MLE and our current approach is really an answer to "what is the best truth I can assign to these model parameters" which is not exactly what we want to learn.
It is also true that a function of an estimate (current approach) is _not_ the same as an estimate of a function.

Proposed Solution
-----------------

I think a Bayesian approach would better fit the question we are asking, eg. "What is the best estimate I can make for the zero noise limit?"
We would need to depend on a python stats package to assist with this, but I don't think that's too bad here.

I have written a brief summary of both current and proposed Bayesian solution with some LaTeX math here: 
[BAYESAN.pdf](https://github.com/unitaryfund/mitiq/files/5456940/BAYESAN.pdf)

I did consult with @cgranade to make sure I got the details right on the write up :)

**Comment by andreamari** [comment]
Thanks @crazy4pi314 !
Bayesian ZNE has always been one of our "dreams" both for research and for Mitiq. I completely agree that it would very appropriate for the task of estimating extrapolations.

However, I also think that the current MLE approach is not unjustified and has its own advantages:
- it requires minimal assumptions on the model (no priors, less initialization data)
- it is theoretically very simple (every Mitiq user understands what is happening and would be able to define custom models)
- it is computationally very efficient to evaluate (no integrals over probability distributions).
- it seems to work, which is always a good sign.

My view on this issue (this is just my personal opinion), is that it would be very good to add Bayesian estimation as you suggested but is should probably be an additional feature and not a replacement of the current MLE methods. For example it could take the form of a new `BayesFactory` class in `mitiq.zne.inference` . 

Two comments on the pdf notes:
- The current idea of Mitiq `executor` functions is that they should directly return expectation values, which usually correspond to averages over many shots (typically 10^4 - 10^5). So, I guess, the Gaussian noise assumption is not so bad. 
- I agree that, if one uses a Bayesian approach, it would be nice to directly use the raw data (the single-shot clicks) as suggested in the pdf. So in this case we would need to re-think the structure of a typical `executor` function.

**Comment by andreamari** [comment]
Thanks @cgranade !

I am definitely not an expert, but can we say that MLE roughly corresponds to a particular case of a Bayesian estimation where a uniform prior distribution is assumed for the model parameters? 
In this sense I agree that I said something wrong when I wrote that MLE "requires minimal assumptions": it actually requires more since it picks a specific prior. What I wanted to say is that, by piking a flat prior, the initial ignorance about the model parameters is maximized. But I think this is a minor issue.

The main point is that there is a trade-off between the generality of the inference framework and the simplicity of the theory/code implementation. Fitting a line and taking the intercept is a very intuitive way of doing zero-noise extrapolation which any user and contributor of Mitiq would understand. On the other hand it would be awesome to have at disposal a more advanced Bayesian method which, by construction, it would take into account physical constraints and would also output a full probability distribution for the zero-noise limit.

For this trade-off reason I think it would be really nice to have both methods in Mitiq.
