### ISSUE TITLE
Checking Local Tests in documentation needs changes

### ISSUE THREAD

**Issue by purva-thakre** [unitaryfund/mitiq#456]
Issue Description
-----------------
In [this section ](https://mitiq.readthedocs.io/en/latest/contributing.html#checking-local-tests), if you want to run tests for pyQuil and Qiskit plugins `make test` needs to be changed to either `make test-pyquil` or `make test-qiskit`. 

`test`, `test-pyquil` and `test-qiskit` are different targets in `Makefile`. 

Possible Proposed Changes
-----------------

1. If the tests for both pyQuil and Qiskit plugins are to be run together, `Makefile` could be changed with a `new_target` executing both `test-pyquil` and `test-qiskit`. Then the documentation could be updated with `make new_target`. 

2. If the tests for both pyQuil and Qiskit plugins are to be run separately, documentation could be updated by adding separate `make test-pyquil` and `make test-qiskit` respectively.

**Comment by rmlarose** [comment]
Good catch! The problem here is just that there is a typo in the [contributing docs](https://mitiq.readthedocs.io/en/latest/contributing.html#checking-local-tests):

![image](https://user-images.githubusercontent.com/32416820/100489543-b3125f80-30e2-11eb-84f8-e28cd9055ea4.png)

This should be

```
make test-pyquil
make test-qiskit
```

Note that `make test-all` can be used to test everything.

**Comment by purva-thakre** [comment]
Ah. I'll make the edits.

**Comment by rmlarose** [comment]
Thanks @purva-thakre
