### ISSUE TITLE
Add option to inform inference model on bounded results

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#472]
It has been brought up if the current inference models in the model `Factories` can be informed of bounded results, e.g., an expectation value bounded between [X_min,X_max]. Since this feature is orthogonal to fitting model, I wonder if it would possible to add a `bounded` method for all relevant factories, or if the simple fitting we use for inference cannot be informed of this.

**Comment by rmlarose** [comment]
It's very easy to include bounds as arguments to extrapolate functions and clip the result. What do you think @andreamari?

**Comment by andreamari** [comment]
I think there are different ways of adding information about bounds:

1. Extrapolating and then clipping. I don't think this is a very clean approach from a statistical point of view. Moreover this could be done by the user very easily after the Mitiq pipeline e.g. `np.clip(execute_with_zne(.... ` .
2. Doing a an informed fit which takes into account constraints and bounds on the fit parameters. In `scipy.curve_fit` there is this option while in `np.polyfit` I think there isn't. This could be done by replacing `np.polyfit` with `scipy.curve_fit` and changing the `extrapolate` function but would require other changes too. E.g. we would need to set and store the bounds for each parameter at the initialization of the factory, giving to the user precise information about the ansatz and the order of parameters, etc.  
3. Creating a generic `LmfitFactory` class (based on https://lmfit.github.io/lmfit-py/index.html) which could be used by advanced users for doing advanced extrapolations. In this case the user could define a custom ansatz by defining an `lmfit.Model` (the ansatz) with custom constraints on the parameters and with any other option compatible with lmfit. After this, the factory could be simply initialized as `fac = LmfitFactory(scale_factors, lmfit_model)`. If we don't like `lmfit` we could introduce a generic ScipyFactory in a similar way.
4. We could also define a generic ByesFactory where a custom model could be defined (e.g. with PyMC (https://github.com/pymc-devs/pymc3) with info about parameters bounds, parameters prior distributions, etc.. The model could then be passed to the factory as an initialization parameter E.g. `fac = ByesFactory(scale_factors, pymc_model)`.  Note this related also to existing issues (#418,  #471).

Personally, I would vote for option (3) and (4). The reason is that, instead of increasing too much the customization of Mitiq factories, at some point it becomes more practical to directly let the user define custom fit model and pass this object to a generic  factory. Option (2) is not so bad.  I would avoid option (1).

**Comment by rmlarose** [comment]
Cursory response: Agree on essentially all points. I agree (2) is easiest implementation-wise, but I also agree full generality is best. I'll have a look into links in (3) and (4) and respond more deeply. One other thing to take into consideration with this discussion is incorporating test data.

**Comment by rmlarose** [comment]
Closing this as option 4 (Bayesian fit) was implemented in #471.
