### ISSUE TITLE
Qubit-dependent vs qubit-independent representations in PEC

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#504]
Consider PEC with the circuit:

```python
import cirq

qreg = cirq.LineQubit.range(2)
circuit = cirq.Circuit(cirq.H.on(q) for q in qreg)
print(circuit)
# 0: ───H───
# 
# 1: ───H───
```

Strictly speaking, there are two operations in this circuit, although they have the same gate. So, if someone wants to do PEC and provides only one representation:

```python
from mitiq import pec

h_op = cirq.Circuit(cirq.ops.H.on(qreg[0]))
rep = pec.OperationRepresentation(
    ideal=h_op,
    basis_expansion={pec.NoisyOperation(h_op): 1.0}  # Or whatever.
)
print(rep)
# 0: ───H─── = 1.000*0: ───H───
```

Then `execute_with_pec` will complain it doesn't know how to represent `1: ───H───`:

```python
pec.execute_with_pec(circuit, lambda c: 1.0, representations=[rep])
# ValueError: Representation of ideal operation 1: ───H─── not found in provided representations.
```

We should support some notion of "this operation applies to all qubits" in addition to the current "this operation applies only to this qubit/these qubits." 

My current guess for the best way to do this is in `OperationRepresentation`, for example allowing a gate with just a placeholder qubit, or perhaps a method like `extend_to(these_qubits)`. Note the latter already exists in `NoisyOperation`. But, I haven't thought it through much - other ideas welcome. 

Refs:
- https://github.com/unitaryfund/mitiq/pull/500#issuecomment-763553474

**Comment by rmlarose** [comment]
Alternative option is to skip operations without known representations. (This might be an interesting theoretical pursuit.)

**Comment by andreamari** [comment]
> Alternative option is to skip operations without known representations. (This might be an interesting theoretical pursuit.)

Having this feature as default or as optional would be indeed very useful.
E.g  if I don't want to mitigate single-qubit gates I simply don't represent them and Mitiq will just apply single-qubit gates without sampling. With the current setup, for each single-qubit gate, we would need to define a trivial  `OperaitonRepresentation` with only one term in the basis expansion.

However I think the problem raised by this issue is different: how do we define _qubit-dependent_ and  _qubit-independent_ operations?
My proposal for (optionally) defining qubit independent operations is something like this:

op_rep = OperationRepresentation(ideal_operaiton, basis_expansion, qubit_independent = True)

An then we need to replace the [search loop in `sample_sequence`](https://github.com/unitaryfund/mitiq/blob/74253d72da759d290c8c9cf7273108df79aeb1cb/mitiq/pec/sampling.py#L67):
```
for representation in representations:
    if _equal(representation.ideal, ideal, require_qubit_equality=True):
        operation_representation = representation
         break
```

with a something like this:

```
for representation in representations:
    if _equal(representation.ideal, ideal, require_qubit_equality=True):
        operation_representation = representation
        break

if operation_representation is None:
  for representation in representations:
        if representation.is_qubit_independent and _equal(representation.ideal, ideal, require_qubit_equality=False):
              operation_representation = representation
              break

```
where the first loop look for a representation with the same qubits and, if it fails, the second loop looks for qubit independent representations.

**Comment by rmlarose** [comment]
> > Alternative option is to skip operations without known representations. (This might be an interesting theoretical pursuit.)
> 
> Having this feature as default or as optional would be indeed very useful.
> E.g if I don't want to mitigate single-qubit gates I simply don't represent them and Mitiq will just apply single-qubit gates without sampling. With the current setup, for each single-qubit gate, we would need to define a trivial `OperaitonRepresentation` with only one term in the basis expansion.
> 
> However I think the problem raised by this issue is different: how do we define _qubit-dependent_ and _qubit-independent_ operations?

Ah yeah, I'm conflating two separate ideas here. Let me open another issue for skipping operations without known representations.

**Comment by rmlarose** [comment]
Rest of proposal seems reasonable to me. You have to be careful with the latter check 

```python
if operation_representation is None:
  for representation in representations:
        if representation.is_qubit_independent and _equal(representation.ideal, ideal, require_qubit_equality=False):
              operation_representation = representation
              break
```

to add the operation on the desired qubit(s) in the sampled circuit. Probably all of the PEC types need to support some notion of "placeholder qubit(s)" like we are discussing here.
