### ISSUE TITLE
Setup GH action to draft release notes automatically

### ISSUE THREAD

**Issue by crazy4pi314** [unitaryfund/mitiq#565]
Using this: https://github.com/release-drafter/release-drafter or similar

**Comment by purva-thakre** [comment]
@crazy4pi314 Just to check - the release notes are a list of all of the PR's that went into releasing the latest version like shown [here](https://github.com/release-drafter/release-drafter/blob/master/design/screenshot-2.png) ?

**Comment by crazy4pi314** [comment]
Yeah, you can see the running doc we have in the repo here: https://github.com/unitaryfund/mitiq/blob/master/CHANGELOG.md Ideally the action can just grab the text from this file/and or help generate it.

**Comment by purva-thakre** [comment]
Yes, I was confused as to why this was created as an issue considering there's a changelog. The discussion at the community meeting clarified this. Thanks !

**Comment by purva-thakre** [comment]
@crazy4pi314 Do you want the [categories](https://github.com/release-drafter/release-drafter#categorize-pull-requests) for this to be separated by quantum and non-quantum changes ? Looking at the list of [issue labels](https://github.com/unitaryfund/mitiq/labels), I am thinking both could have sub-categories - bug fix, documentation change/addition, enhancement or feature.

**Comment by crazy4pi314** [comment]
I don't see a strong need to have the labels separate categories for the listings, I think we would need to have more rigorous labeling conventions as you suggest 😋 I'll raise this in the community call on friday, but let's treat label specific sections as a later upgrade 👍

**Comment by grmlarose** [comment]
Decided at Mitiq meeting to go with https://github.com/release-drafter/release-drafter and this will be triggered on PRs to the release branch.

**Comment by purva-thakre** [comment]
Above linked PR does not solve this issue. 

In case anyone else wants to work on this, here's a list of things I tried or was planning to try : 

I first tried to use[ github-changelog-generator](https://github.com/github-changelog-generator/github-changelog-generator) to automate updates to `Changelog.md`. The changelog generator is available as a workflow [here](https://github.com/heinrichreimer/action-github-changelog-generator). The issue with using this workflow is an error with how the generator uses tags. Even if you try to ignore tags, the generator still fails to add a commit to the changelog file with an error related to `--since-tag`. There's a discussion about this [at the project's channel](https://gitter.im/github-changelog-generator/chat?at=5f57456cec534f584fedf00d) as well but due to lack of contributors, the issue will not be resolved soon. If this action would have worked properly then there would have been an additional action to auto commit the lines added in changelog back to master via [this action](https://github.com/stefanzweifel/git-auto-commit-action). 

In addition, since you want a commit message to be read by above actions (or any other such automated action) to add to changelog, there would have been a proposed change [to the format of commit messages](https://www.conventionalcommits.org/en/v1.0.0/).  Since the old changelog file is updated manually, it was renamed as `History.md`.  A successful workflow would have added a new `Changelog.md` with appended lines from `History.md`. 

Here's a list of automated changelog/release actions I was planning on trying : 

- https://github.com/conventional-changelog/conventional-changelog
- https://github.com/conventional-changelog/standard-version
- https://github.com/cookpete/auto-changelog
- [This link](https://betterprogramming.pub/create-your-own-changelog-generator-with-git-aefda291ea93) discusses creating a changelog from the log difference but it is not a good idea [based on the discussions I found](https://stackoverflow.com/questions/3523534/what-are-some-good-ways-to-manage-a-changelog-using-git#comment39965351_22492425).
