### ISSUE TITLE
Possible misplaced code cells in documentation

### ISSUE THREAD

**Issue by purva-thakre** [unitaryfund/mitiq#586]
Pre-Report Checklist
--------------------

- [x] I am running the latest version of mitiq
- [x] I checked to make sure that this bug has not already been reported

Issue Description
-----------------
Couple of code cells in documentation appear at the end instead of at the beginning. For the [variational circuit example](https://mitiq.readthedocs.io/en/stable/examples/simple_landscape.html#acknowledgements),  a code cell for `import mitiq` appears after acknowledgements. Another misplaced code cell is in the [maxcut example](https://mitiq.readthedocs.io/en/stable/examples/maxcut-demo.html#references), where `mitiq.about()` appears after references. 

If these are intentional then feel free to close the issue. If not, I can work on it.

**Comment by rmlarose** [comment]
It was intentional to show the version information of Mitiq, with the unstated convention that it appears at the end of tutorials. I think it looks weird as well, though, and it seems redundant since RTD tells you latest or stable. If @nathanshammah or @crazy4pi314 don't disagree I would say feel free to remove it @purva-thakre.

**Comment by purva-thakre** [comment]
Closing this because version information code cells only look out of place when their output is not shown. See comment in above PR.
