### ISSUE TITLE
Add an `extensions` module for `mitiq_package`s?

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#667]
Right now, we have `mitiq_cirq`, `mitiq_qiskit`, and `mitiq_pyquil` as submodules for interfacing with the three supported "front-end" packages.

Soon, we will have `mitiq_braket` (#590), `mitiq_pennylane`, and potentially others. This starts to clutter the namespace.

## Proposal 1

Add `mitiq.extensions` where `mitiq_qiskit` etc. all live.

## Other ideas?

Please propose them below, or upvote proposal 1!

**Comment by andreamari** [comment]
Proposal 1 is good for me.

**Comment by purva-thakre** [comment]
Is this still open for discussion ? Just wanted to check before I start working on this.

**Comment by rmlarose** [comment]
@purva-thakre yes in the sense that we still need to decide when and how (mostly in terms of deprecation) to introduce this change.

**Comment by purva-thakre** [comment]
@rmlarose Gotcha.

>  still need to decide when and how (mostly in terms of deprecation) to introduce this change

Just a couple of questions about this. 
- 'when' refers to which release version ?
- 'how' refers to how to structure the deprecation warnings in[ this file](https://github.com/unitaryfund/mitiq/blob/master/mitiq/_deprecations.py), defining a particular [deprecation decorator](https://stackoverflow.com/questions/739654/how-to-make-function-decorators-and-chain-them-together) for all extensions or the desire to use a [deprecation package](https://deprecation.readthedocs.io/en/latest/) ?

**Comment by rmlarose** [comment]
Yes to both! 

> A couple of questions about this.
> 
> * 'when' refers to some release version ?
> * 'how' refers to how to structure the deprecation warnings in[ this file](https://github.com/unitaryfund/mitiq/blob/master/mitiq/_deprecations.py), defining a particular [deprecation decorator](https://stackoverflow.com/questions/739654/how-to-make-function-decorators-and-chain-them-together) for all extensions or the desire to use a [deprecation package](https://deprecation.readthedocs.io/en/latest/) ?

**Comment by rmlarose** [comment]
Putting this as p0 because, as discussed @ Mitiq meeting, we want to have this for the next release after adding support for Braket.

**Comment by andre-a-alves** [comment]
As discussed in the last meeting, below are a few data points for us to consider when choosing the module name - specifically generally agreed upon definitions of some words as well what names are used by a few other projects - for us to discuss at today's meeting.

## Other Projects
### Pennylane
Pennylane uses "interfaces" for NumPy, PyTorch, JAX, and TensorFlow. What we call front-ends they tend to call types of Devices.
### AirlineQ
In AirlineQ, our front-ends are referred to as "compilation frameworks."
### Tequila
Tequila refers to them as "backends."

## Definitions
### interface
(computing) shared boundary across which two or more separate components of a computer system exchange information.
(OOP) an abstract type that contains no data but defines behaviors as method signatures.
### integration
(PC Mag) The combining of...components so that they work together.
### library
(computer science) a collection of non-volatile resources used by computer programs. These may include...classes...or type specifications.
