### ISSUE TITLE
Large error rate when using mitigation method

### ISSUE THREAD

**Issue by peachnuts** [unitaryfund/mitiq#683]
Pre-Report Checklist
--------------------

- [x] I am running the latest version of mitiq
- [x] I checked to make sure that this bug has not already been reported

How to Reproduce
----------------
I used `flod_gate_at_random` method to generated `folded_circuits` with scales factors in the following code. 
The circuit has 20 gates, including 11 cnots. I executed the folded circuits on an IBM quantum device.
Then, I tried different extrapolation methods. I think the obtained expectation values are reasonable since the result decreases as the circuit depth increases.  However, when I used the `RichardsonFactory` method, the error rate is always larger than one (I tried several other different circuits using this method) and is way larger than the error rate before mitigation.  Is it normal to have this kind of result? Is this result due to the size of the benchmark or the extrapolation method? I tried other benchmarks and sometimes `PolyFactory` with order 2 also gives an error rate of more than one.

### Code Snippet

```python
scale_factors = [1., 1.5, 2., 2.5]
expectation_values = [0.623046875, 0.4951171875, 0.2904052734375, 0.182861328125]

from mitiq.zne.inference import LinearFactory, RichardsonFactory, PolyFactory

zero_limit = PolyFactory.extrapolate(scale_factors, expectation_values, order=2)
print(f"Error with PolyFactory.extrapolate method: {abs(1.0 - zero_limit):.4f}")

zero_limit = LinearFactory.extrapolate(scale_factors, expectation_values)
print(f"Error with LinearFactory.extrapolate method: {abs(1.0 - zero_limit):.4f}")

zero_limit = RichardsonFactory.extrapolate(scale_factors, expectation_values)
print(f"Error with RichardsonFactory.extrapolate method: {abs(1.0 - zero_limit):.4f}")

```

### Error Output

```
Error with PolyFactory.extrapolate method: 0.0122
Error with LinearFactory.extrapolate method: 0.0683
Error with RichardsonFactory.extrapolate method: 1.0472
```

Environment Context
-------------------
```python
Mitiq Version:	0.8.0
Core Dependencies
-----------------
Cirq Version:	0.10.0
NumPy Version:	1.20.1
SciPy Version:	1.4.1
Optional Dependencies
---------------------
PyQuil Version:	Not installed
Qiskit Version:	0.24.1
Python Version:	3.8.5
Platform Info:	Linux (x86_64)

```

**Comment by andreamari** [comment]
Hi @peachnuts, thanks for this issue. 
I think this is not a bug but the expected behavior of the different extrapolation methods.
Linear extrapolation corresponds to a polynomial fit of `order=1`, while Richardson extrapolation, in this case, corresponds to a polynomial fit of `order=len(scale_factors)-1=3`.

So your case is a situation in which the extrapolation gets worst as you increase the order of the polynomial fit. This is a typical problem of ZNE and of polynomial fitting in general (see also this [note](https://mitiq.readthedocs.io/en/stable/guide/guide-error-mitigation.html#limitations-of-zero-noise-extrapolation)). More insight can be obtained after plotting the results with the following code:

```
poly_fac = PolyFactory(scale_factors, order=2)
poly_fac._batch_populate_instack()
poly_fac._outstack = expectation_values
zero_limit = poly_fac.reduce()
print(f"Error with PolyFactory.extrapolate method: {abs(1.0 - zero_limit):.4f}")
_ = poly_fac.plot_fit()
plt.legend()
plt.title("PolyFactory order=2")
plt.show()
```
![image](https://user-images.githubusercontent.com/46054446/118653542-f1621f00-b7e7-11eb-8496-2b8c2d600c4c.png)

```
ric_fac = RichardsonFactory(scale_factors)
ric_fac._batch_populate_instack()
ric_fac._outstack = expectation_values
zero_limit = ric_fac.reduce()
print(f"Error with PolyFactory.extrapolate method: {abs(1.0 - zero_limit):.4f}")
_ = ric_fac.plot_fit()
plt.legend()
plt.title("RichardsonFactory")
plt.show()
```
![image](https://user-images.githubusercontent.com/46054446/118653587-fb841d80-b7e7-11eb-826a-a18f9cc3e438.png)


From the plots it is evident that `RichardsonFactory` is over-fitting your data and producing a bad extrapolation. This phenomenon is usually stronger for large statistical fluctuations of the data and increasing the number of shots can reduce this effect. Anyway, whatever is the precision of your data, there will always be an optimal value of `order` beyond which bad extrapolations will happen.

**Comment by peachnuts** [comment]
Hi Andrea!
Thanks for your explanation and your code snippets! It really helped to solve my questions!
Sorry that I didn't think this is a bug but the bug label was added in default when I created this issue...
