### ISSUE TITLE
More explicit names for NoisyOperation arguments?

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#703]
Currently a `NoisyOperation` is initialized with two arguments `ideal` and `real`.
```python
class NoisyOperation:
    """An operation (or sequence of operations) which a quantum computer can
     actually implement.
     """

    def __init__(
        self, ideal: QPROGRAM, real: Optional[np.ndarray] = None
    ) -> None:
        """Initializes a NoisyOperation.

        Args:
            ideal: The operation a noiseless quantum computer would implement.
            real: Superoperator representation of the actual operation
                implemented on a noisy quantum computer, if known.
```

I wonder if it is better to use more explicit names. Some proposals:

0. `ideal` and `real` (keep current names )
1. `operation` and `superoperator`
2. `circuit` and `superoperator`
3. `operation` and `channel_matrix`
4. `circuit` and `channel_matrix`

**Comment by purva-thakre** [comment]
I like option 3 with a small change - `ideal_operation` and `channel_matrix`

**Comment by rmlarose** [comment]
I wouldn't use `operation` because it always has to be a circuit. `circuit` is ok but I would prefer `unitary` for this - both circuits and operations have unitaries, and unitary tends to convey noiseless.

For `real`, I agree it's not descriptive enough. (Although I do like how `ideal` and `real` sit together.) I tend to like `superoperator` for this but have less strong feelings.

So, I would write-in for `unitary` and `superoperator`.
