### ISSUE TITLE
What is `_deprecations.py` doing?

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#723]
[It](https://github.com/unitaryfund/mitiq/blob/master/mitiq/_deprecations.py) appears to define four functions which aren't used anywhere. Am I missing something?

**Comment by andreamari** [comment]
The are used here https://github.com/unitaryfund/mitiq/blob/master/mitiq/__init__.py . The intention is to raise a deprectation error when people try to use `from mitiq import mitigate_executor/zne_decorator/execute_with_zne` instead of from `mitiq.zne import mitigate_executor/zne_decorator/execute_with_zne`.
