### ISSUE TITLE
Some documentation is not being tested in CI

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#766]
If you copy-paste the [IBMQ example](https://mitiq.readthedocs.io/en/stable/examples/ibmq-backends.html) into a [colab](https://colab.research.google.com/drive/1UK8mTyVIY673U23zXjUbhft8BU_M8DQs?usp=sharing), there is an error.

![image](https://user-images.githubusercontent.com/32416820/123715315-03eb6180-d846-11eb-81db-44bcf858e942.png)

(Should be `from mitiq import zne` instead of `import mitiq` above.)

We should be testing examples in CI to make sure they run and catch errors like this.

**Comment by nathanshammah** [comment]
We are running the tests on the documentation: 
https://github.com/unitaryfund/mitiq/blob/58fdff01d53c0b9cf9b068d60e005c094ca6ffcb/.github/workflows/test.yml#L52

In the user guide, we have 76 `testcode` directive instances. .

With regards to test-code blocks in notebooks, we can look into that. The way myst works is by building the docs by running the notebooks (be them rst or other formats), so all output seen in the html documentation online has been generated by some code in CI. 

The reason why this is not picked up seems to be due to a global requirement that is set in the `conf.py`, which sets an alias import, https://github.com/unitaryfund/mitiq/blob/255df184eca7a1b3e60455c281c3b884719ff876/docs/source/conf.py#L157-L168. We could remove that.

**Comment by rmlarose** [comment]
Thanks for noting the global config. I removed it in #804 to test and the docs build passes, so there is something else going on.

**Comment by andreamari** [comment]
The problem seems to be related to using `.. testcode:: python` instead of just `.. testcode::` . 
See last commit `[test] try removing "python" style label` of #804   (i.e. 9bcb927) .

**Comment by rmlarose** [comment]
Thanks @andreamari. There's a lot of other `.. testcode:: python` directives in that file, I guess those should be removed as well...?
