### ISSUE TITLE
New technique: Quantum subspace expansion

### ISSUE THREAD

**Issue by crazy4pi314** [unitaryfund/mitiq#818]
### Problem

Mitiq needs more error mitigation techniques.

The [Quantum subspace expansion](https://www.nature.com/articles/s41467-020-14341-w) paper outlines a new error mitigation technique which involves error correcting codes. This is estimated to take ~6 months dev time.

**Related papers**
- [Symmetry verification](https://arxiv.org/abs/1807.10050)

### Rough requirements

- Requires ability to specify an error correcting code.

**Comment by nathanshammah** [comment]
Just a note that #575 and #599 were somewhat related.

**Comment by rmlarose** [comment]
Colab with some prototype subspace expansion code: https://colab.research.google.com/drive/1hN8jtBK9PBVCVvT8WkcNmgHSQbBkSq00?usp=sharing

**Comment by bubakazouba** [comment]
Hello,
We have been working on this error mitigation technique and we have an RFC ready: [Request For Comments (RFC) — Error Mitigation by Subspace Expansion](https://docs.google.com/document/d/1JyQAwiw8BRT_oucZ6tQv0id6UhSdd3df1mNSPpOvu1I/edit#).

We also have a PR ready as well that I'll be sending soon.

**Comment by andreamari** [comment]
[bubakazouba](https://github.com/bubakazouba), thanks for the very good work! we'll review your RFC soon!

**Comment by andreamari** [comment]
The [Request For Comments (RFC) — Error Mitigation by Subspace Expansion](https://docs.google.com/document/d/1JyQAwiw8BRT_oucZ6tQv0id6UhSdd3df1mNSPpOvu1I/edit#) has been approved!


The current draft PR is very useful to have an idea of the overall code but it is hard to review and to merge in a single shot.
So for the implementation, we suggest to sequentially focus on the following sub-issues and related sub-PRs:

- Adding support for multiplication of Observables (and or PauliStrings)
- Implement the main utility functions into a new module called `mitiq/sse/`    (`sse` = sub-space expansion)
- Implement standard Mitiq functions: `execute_with_sse`, `mitigate_executor`, `sse_decorator` without supporting the case `observable=None` (consistently with the current draft).
- Optional SSE improvement: support `observabe=None` by appending Paulis to circuits instead of absorbing them into the `Observable`.

**Comment by andreamari** [comment]
Hi @bubakazouba, 
thanks for all you have already done about QSE!
Are you also interested in working on #1812  in the next month?
No problem if you can't, I am asking just to better plan the main topics for the next milestone.

**Comment by bubakazouba** [comment]
> Hi @bubakazouba, thanks for all you have already done about QSE! Are you also interested in working on #1812 in the next month? No problem if you can't, I am asking just to better plan the main topics for the next milestone.

Yes I plan to wrap it up early july.
