### ISSUE TITLE
Allow `Executor.run` to accept a sequence of keyword arguments

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#952]
And use this in `zne.BatchedFactory.run` (see inline TODO).

## Current behavior

Right now `Executor.run` accepts keyword args and passes them to the executor. However, the same keyword args are passed each time.

## Desired behavior

Ability to call `Executor.run` with a sequence of (different) keyword args.

## Questions / considerations

If `len(kwargs_list) == len(circuits)`, I think you'd have to run all circuits serially (see question below). If `len(kwargs_list) == 1`, batching can be done (this is the current behavior).

Should a set of `kwargs` *for each batch* be allowed? Something like `circuits = [circuit1, circuit2, circuit3, circuit4]` with `max_batch_size = 2` so that the first batch is `batch1 = [circuit1, circuit2]` and the second is `batch2 = [circuit3, circuit4]`. If `kwargs_list [kwargs1, kwargs2]`, should this

1. Do `self._call_executor(batch1, kwargs1)` then `self._call_executor(batch2, kwargs2)`?
2. Raise an error?
3. Other?

## Misc

Origin: https://github.com/unitaryfund/mitiq/pull/948#discussion_r716844017

Related: #484

**Comment by andreamari** [comment]
I think I am in favor of just supporting a fixed set of options `kwargs` to be used for the execution of all the circuits. 
If we need to use different `kwargs` we can make multiple independent calls to Executor.run.

There wouldn't be a loss of efficiency since, in a typical setting, circuits with different options cannot be batched together.

**Comment by rmlarose** [comment]
I agree with this. Closing and will update #948 appropriately.
