### ISSUE TITLE
Different factories use different points for ZNE?

### ISSUE THREAD

**Issue by atmalik123** [unitaryfund/mitiq#991]
Do different factories sample different points? I used ZNE with a polynomial factory and a linear factory with the same scale_factors, yet the points they use look different. Is this supposed to happen? If so, can someone explain why? Isn't it impossible to compare the effectiveness of different factories if they use different points for extrapolation?

![k](https://user-images.githubusercontent.com/29261370/137790706-0d02640e-28ab-4b99-9276-fd449902f5fc.PNG)
![e](https://user-images.githubusercontent.com/29261370/137790971-21b6db9b-5314-4d6e-ba01-8555b4be8470.PNG)

**Comment by rmlarose** [comment]
The scale factors (x-axis values) are the same in both plots. The expectation values (y-axis values) are different presumably because you are computing expectation values via sampling.

If you would like to do different extrapolation techniques with the same data (i.e., y-axis values):

1. Collect the data by computing the expectation value at each scale factor.
2. Use `Factory.extrapolate(scale_factors, expectation_values)` for the `Factory`s you are considering.

i.e.

```python
from mitiq import zne

circuit =  # Something.
def execute(circuit) -> float:
   # Computes expectation value.

scale_factors = [1, 2, 3]
expectation_values = [execute(zne.scaling.fold_global(circuit, s) for s in scale_factors]

# Linear extrapolation.
zne.LinearFactory.extrapolate(scale_factors, expectation_values)

# Polynomial extrapolation.
zne.PolyFactory.extrapolate(scale_factors, expectation_values, order)
```

I will close this, but please re-open or continue the conversation as appropriate. You can also continue the conversation in our Discord http://discord.unitary.fund.

**Comment by atmalik123** [comment]
![k](https://user-images.githubusercontent.com/29261370/138187454-ab397053-1edd-4e65-b674-53dff3b2707d.PNG)

I'm getting this error

**Comment by andreamari** [comment]
Hi @atmalik123,
there is a small syntax error:
`execute(zne.scaling.fold_global(circuit, s) `
should be
`execute(zne.scaling.fold_global(circuit, s))`

**Comment by atmalik123** [comment]
Before I was defining a factory l_fac and p_fac first so I could use plot_fit(), but in the solution given they use LinearFactory and PolyFactory directly. How can I use plot_fit() on these?
